server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false # 关闭thymeleaf缓存；这样方便开发的时候实时看见变化。
  rabbitmq:
    host: 192.168.217.128   # 端口默认是5672
    virtual-host: /leyou   # 虚拟主机是我们自己创建的;其实就相当在linux下的目录 /
    username: leyou    # 用户名和密码都是在RabbiMQ网页客户端创建的
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5

